### ISSUE TITLE
базовый функционал compound nft

### ISSUE THREAD

**Issue by fomotoshi** [battlemon-project/contracts#7]

**Comment by ChzenChzen** [comment]
@tonborzenko на последнем этапе реализации этой фичи. В данный момент, нахожусь на стадии обдумывания интерфейса взаимодействия с фронтом. 

Пока думаю над версией, когда на фронте в конструкторе человек составляет свое compound nft и хочет этот результат застейтить в блокчейне. соответственно нужен формат поставки этих данных.  мне из инфы нужно только  токен с `id1` в который вставляется токен с `id2`.

например: 
```
[
   {"1": "2"},
]
```
означает что в токен с `id1` вставлен токен с `id2`.

пример с более сложной вложенностью.

тут в нфт с id `1`, вставляется нфт с id `2`,
а в нфт с id `2`, вставляется нфт с id `3`.
```
[
  {"1": "2"},
  {"2": "3"},
]
``` 

тут в нфт с id `1`, вставляется нфт с id `2`,
а в нфт с id `2`, вставляется нфт с id `3` и id `4`.
```
  {"1": "2"},
  {"2": "3"},
  {"2": "4"},
```

можно для простоты вообще передавать как массив чисел.
```
[1, 2, 2, 3, 2, 4]
```
думаю даже так оптимальнее

**Comment by tonborzenko** [comment]
Лучше первый вариант, мне на фронте массив из объектов будет проще распарсить чем массив из цифр.

**Comment by ChzenChzen** [comment]
@tonborzenko так тебе парсить не надо ничего, тебе нужно с генерировать и пепедать это мне. парсить я буду.

**Comment by tonborzenko** [comment]
А просмотр как мне осуществлять? Мне нужен один механизм на просмотр и
создание

сб, 18 дек. 2021 г., 16:40 ChzenChzen ***@***.***>:

**Comment by ChzenChzen** [comment]
@tonborzenko просмотр чего?

**Comment by tonborzenko** [comment]
Думаю нам понадобится функционал просмотра соединённых nft, и вывод
собранной 3д модели на ее основе.

вс, 19 дек. 2021 г., 16:14 ChzenChzen ***@***.***>:

**Comment by ChzenChzen** [comment]
@tonborzenko да тоже щас подумал и понял, короче ввод сделаем массивом чисел, но на вывод тебе в любом случае больше инфы надо, потому что, если я тебе дам просто id токенов, тебе придется колить много вызовов `nft_token`, логичнее тебе сразу пеередать развесистый json из которого будет все тебе понятно )
